[package]
name = "attribute-store"
version = "0.0.0"
edition = "2021"

[dependencies]
thiserror = "1.0.61"
regex = "1.10.5"
async-trait = "0.1.80"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
