[package]
name = "attribute-grpc-api"
version = "0.0.0"
edition = "2021"

[dependencies]
prost = "0.12.6"
serde = { version = "1.0.203", features = ["derive"] }
tonic = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"
